import type { Metadata } from "next";
import { ArrowUpIcon } from "lucide-react";
import { Affix, ThemeAdapter } from "@kadoui/react";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning>
      <head>
        <ThemeAdapter />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div id="root">
          {children}

          <Affix className="affix top-center right-3 btn btn-fill btn-square group data-[state=false]:scale-90">
            <ArrowUpIcon className="btn-icon-size transition-transform duration-300 group-data-[state=false]:translate-y-full" />
          </Affix>
        </div>
      </body>
    </html>
  );
}
